
services:
  reverse-proxy:
    ports:
      - "80:80"
      - "8000:8000"
      - "3000:3000"

  app:
    volumes:
      - .:/app

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
###< doctrine/doctrine-bundle ###

  ml:
    ports:
      - "8001:8001"
    volumes:
      - ./ml:/app
      - huggingface_cache:/root/.cache/huggingface
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "8002:8000"
    volumes:
      - .:/docs
    command: serve --dev-addr=0.0.0.0:8000

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    volumes:
      - ./docker/adminer/adminer.css:/var/www/html/adminer.css:ro
    depends_on:
      - database

###> symfony/mailer ###
  mailer:
    ports:
      - "1025:1025"
      - "8025:8025"
###< symfony/mailer ###

volumes:
  huggingface_cache:
