
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
###< doctrine/doctrine-bundle ###

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    volumes:
      - ./docker/adminer/adminer.css:/var/www/html/adminer.css:ro
    depends_on:
      - database

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "3000:80"
###< symfony/mercure-bundle ###
