<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260413121529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject VARCHAR(255) DEFAULT NULL, applicant_user_id INT NOT NULL, recruiter_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E9D12B766C ON conversation (applicant_user_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E96179D673 ON conversation (recruiter_user_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_read BOOLEAN NOT NULL, conversation_id INT NOT NULL, sender_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F2A98155E ON message (sender_user_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9D12B766C FOREIGN KEY (applicant_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E96179D673 FOREIGN KEY (recruiter_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F2A98155E FOREIGN KEY (sender_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT fk_7afb50006352511c');
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT fk_7afb50006c066afe');
        $this->addSql('ALTER TABLE admin_action_log ALTER admin_user_id DROP NOT NULL');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT FK_7AFB50006352511C FOREIGN KEY (admin_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT FK_7AFB50006C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9D12B766C');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E96179D673');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F2A98155E');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE message');
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT FK_7AFB50006352511C');
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT FK_7AFB50006C066AFE');
        $this->addSql('ALTER TABLE admin_action_log ALTER admin_user_id SET NOT NULL');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT fk_7afb50006352511c FOREIGN KEY (admin_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT fk_7afb50006c066afe FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
