<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220142708 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, entity_type VARCHAR(255) DEFAULT NULL, entity_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, metadata JSON DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F647A76ED395 ON activity_log (user_id)');
        $this->addSql('CREATE TABLE contact_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recruiter_name VARCHAR(255) NOT NULL, recruiter_email VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, developer_profile_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C9211FE6444A7E ON contact_message (developer_profile_id)');
        $this->addSql('CREATE TABLE developer_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, headline VARCHAR(255) NOT NULL, bio TEXT DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, location_type VARCHAR(255) DEFAULT NULL, experience_level VARCHAR(255) DEFAULT NULL, years_experience INT DEFAULT NULL, is_public BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, avatar_path VARCHAR(255) DEFAULT NULL, cv_pdf_path VARCHAR(255) DEFAULT NULL, github_url VARCHAR(255) DEFAULT NULL, linkedin_url VARCHAR(255) DEFAULT NULL, portfolio_url VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EFC94CA4989D9B62 ON developer_profile (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EFC94CA4A76ED395 ON developer_profile (user_id)');
        $this->addSql('CREATE TABLE developer_profile_position (developer_profile_id INT NOT NULL, position_id INT NOT NULL, PRIMARY KEY (developer_profile_id, position_id))');
        $this->addSql('CREATE INDEX IDX_1101D6D86444A7E ON developer_profile_position (developer_profile_id)');
        $this->addSql('CREATE INDEX IDX_1101D6D8DD842E46 ON developer_profile_position (position_id)');
        $this->addSql('CREATE TABLE education (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, school_name VARCHAR(255) NOT NULL, degree VARCHAR(255) DEFAULT NULL, field VARCHAR(255) DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, developer_profile_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB0A5ED26444A7E ON education (developer_profile_id)');
        $this->addSql('CREATE TABLE experience (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_current BOOLEAN NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, developer_profile_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_590C1036444A7E ON experience (developer_profile_id)');
        $this->addSql('CREATE TABLE experience_technology (experience_id INT NOT NULL, technology_id INT NOT NULL, PRIMARY KEY (experience_id, technology_id))');
        $this->addSql('CREATE INDEX IDX_1BC2EDF146E90E27 ON experience_technology (experience_id)');
        $this->addSql('CREATE INDEX IDX_1BC2EDF14235D463 ON experience_technology (technology_id)');
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_462CE4F55E237E06 ON position (name)');
        $this->addSql('CREATE TABLE profile_skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(255) DEFAULT NULL, years INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, developer_profile_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A9E97BA56444A7E ON profile_skill (developer_profile_id)');
        $this->addSql('CREATE INDEX IDX_A9E97BA55585C142 ON profile_skill (skill_id)');
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E3DE4775E237E06 ON skill (name)');
        $this->addSql('CREATE TABLE technology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F463524D5E237E06 ON technology (name)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE contact_message ADD CONSTRAINT FK_2C9211FE6444A7E FOREIGN KEY (developer_profile_id) REFERENCES developer_profile (id)');
        $this->addSql('ALTER TABLE developer_profile ADD CONSTRAINT FK_EFC94CA4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE developer_profile_position ADD CONSTRAINT FK_1101D6D86444A7E FOREIGN KEY (developer_profile_id) REFERENCES developer_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE developer_profile_position ADD CONSTRAINT FK_1101D6D8DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE education ADD CONSTRAINT FK_DB0A5ED26444A7E FOREIGN KEY (developer_profile_id) REFERENCES developer_profile (id)');
        $this->addSql('ALTER TABLE experience ADD CONSTRAINT FK_590C1036444A7E FOREIGN KEY (developer_profile_id) REFERENCES developer_profile (id)');
        $this->addSql('ALTER TABLE experience_technology ADD CONSTRAINT FK_1BC2EDF146E90E27 FOREIGN KEY (experience_id) REFERENCES experience (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE experience_technology ADD CONSTRAINT FK_1BC2EDF14235D463 FOREIGN KEY (technology_id) REFERENCES technology (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profile_skill ADD CONSTRAINT FK_A9E97BA56444A7E FOREIGN KEY (developer_profile_id) REFERENCES developer_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_skill ADD CONSTRAINT FK_A9E97BA55585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647A76ED395');
        $this->addSql('ALTER TABLE contact_message DROP CONSTRAINT FK_2C9211FE6444A7E');
        $this->addSql('ALTER TABLE developer_profile DROP CONSTRAINT FK_EFC94CA4A76ED395');
        $this->addSql('ALTER TABLE developer_profile_position DROP CONSTRAINT FK_1101D6D86444A7E');
        $this->addSql('ALTER TABLE developer_profile_position DROP CONSTRAINT FK_1101D6D8DD842E46');
        $this->addSql('ALTER TABLE education DROP CONSTRAINT FK_DB0A5ED26444A7E');
        $this->addSql('ALTER TABLE experience DROP CONSTRAINT FK_590C1036444A7E');
        $this->addSql('ALTER TABLE experience_technology DROP CONSTRAINT FK_1BC2EDF146E90E27');
        $this->addSql('ALTER TABLE experience_technology DROP CONSTRAINT FK_1BC2EDF14235D463');
        $this->addSql('ALTER TABLE profile_skill DROP CONSTRAINT FK_A9E97BA56444A7E');
        $this->addSql('ALTER TABLE profile_skill DROP CONSTRAINT FK_A9E97BA55585C142');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE contact_message');
        $this->addSql('DROP TABLE developer_profile');
        $this->addSql('DROP TABLE developer_profile_position');
        $this->addSql('DROP TABLE education');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE experience_technology');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE profile_skill');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE technology');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
