<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260323140751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin_action_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, reason TEXT DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, admin_user_id INT NOT NULL, target_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7AFB50006352511C ON admin_action_log (admin_user_id)');
        $this->addSql('CREATE INDEX IDX_7AFB50006C066AFE ON admin_action_log (target_user_id)');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT FK_7AFB50006352511C FOREIGN KEY (admin_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE admin_action_log ADD CONSTRAINT FK_7AFB50006C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id)');
        $this->addSql('DROP INDEX idx_contact_message_profile_lower_email');
        $this->addSql('DROP INDEX idx_contact_message_profile_created_order');
        $this->addSql('DROP INDEX idx_dev_profile_public_generated_order');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT FK_7AFB50006352511C');
        $this->addSql('ALTER TABLE admin_action_log DROP CONSTRAINT FK_7AFB50006C066AFE');
        $this->addSql('DROP TABLE admin_action_log');
        $this->addSql('CREATE INDEX idx_contact_message_profile_lower_email ON contact_message (developer_profile_id)');
        $this->addSql('CREATE INDEX idx_contact_message_profile_created_order ON contact_message (developer_profile_id, created_at, id)');
        $this->addSql('CREATE INDEX idx_dev_profile_public_generated_order ON developer_profile (is_public, portfolio_generated_at, updated_at)');
    }
}
