<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312183641 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, website VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, industry VARCHAR(255) DEFAULT NULL, size VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, logo_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE favorite_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recruiter_profile_id INT NOT NULL, developer_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DC0304619F31CFEE ON favorite_profile (recruiter_profile_id)');
        $this->addSql('CREATE INDEX IDX_DC0304616444A7E ON favorite_profile (developer_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX favorite_profile_unique_pair ON favorite_profile (recruiter_profile_id, developer_profile_id)');
        $this->addSql('CREATE TABLE job_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, location VARCHAR(255) DEFAULT NULL, location_type VARCHAR(255) DEFAULT NULL, contract_type VARCHAR(255) DEFAULT NULL, experience_level INT DEFAULT NULL, salary_min INT DEFAULT NULL, salary_max INT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recruiter_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_288A3A4E9F31CFEE ON job_offer (recruiter_profile_id)');
        $this->addSql('CREATE TABLE recruiter_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, job_title VARCHAR(255) NOT NULL, work_email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4740AFE9A76ED395 ON recruiter_profile (user_id)');
        $this->addSql('CREATE INDEX IDX_4740AFE9979B1AD6 ON recruiter_profile (company_id)');
        $this->addSql('ALTER TABLE favorite_profile ADD CONSTRAINT FK_DC0304619F31CFEE FOREIGN KEY (recruiter_profile_id) REFERENCES recruiter_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite_profile ADD CONSTRAINT FK_DC0304616444A7E FOREIGN KEY (developer_profile_id) REFERENCES developer_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E9F31CFEE FOREIGN KEY (recruiter_profile_id) REFERENCES recruiter_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recruiter_profile ADD CONSTRAINT FK_4740AFE9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recruiter_profile ADD CONSTRAINT FK_4740AFE9979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE favorite_profile DROP CONSTRAINT FK_DC0304619F31CFEE');
        $this->addSql('ALTER TABLE favorite_profile DROP CONSTRAINT FK_DC0304616444A7E');
        $this->addSql('ALTER TABLE job_offer DROP CONSTRAINT FK_288A3A4E9F31CFEE');
        $this->addSql('ALTER TABLE recruiter_profile DROP CONSTRAINT FK_4740AFE9A76ED395');
        $this->addSql('ALTER TABLE recruiter_profile DROP CONSTRAINT FK_4740AFE9979B1AD6');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE favorite_profile');
        $this->addSql('DROP TABLE job_offer');
        $this->addSql('DROP TABLE recruiter_profile');
    }
}
