<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260421153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les demandes de support utilisateur.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE support_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, requester_display_name VARCHAR(255) NOT NULL, requester_email VARCHAR(180) NOT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1CAD2203A76ED395 ON support_request (user_id)');
        $this->addSql('ALTER TABLE support_request ADD CONSTRAINT FK_1CAD2203A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE support_request DROP CONSTRAINT FK_1CAD2203A76ED395');
        $this->addSql('DROP TABLE support_request');
    }
}
