services:
    App\Tests\Mercure\NullPublisher: ~

    mercure.hub.default:
        class: Symfony\Component\Mercure\MockHub
        arguments:
            - '%env(default::MERCURE_URL)%'
            - '@mercure.hub.default.jwt.provider'
            - '@App\Tests\Mercure\NullPublisher'
            - '@.lazy.mercure.hub.default.jwt.factory'
            - '%env(default::MERCURE_PUBLIC_URL)%'
